#!/usr/bin/python
import os
import broadlink

fifo_path = os.environ['BROADLINK_FIFO_PATH']
addr = os.environ['BROADLINK_ADDR']

if os.path.exists(fifo_path):
    os.remove(fifo_path)

os.mkfifo(fifo_path)

devices = broadlink.discover(timeout=5, discover_ip_address=addr)
devices[0].auth()

while True:
    with open(fifo_path, 'rb') as fifo:
        devices[0].send_data(fifo.read())
