#!/usr/bin/python
import os
from govee_api import api

user = os.environ['GOVEE_EMAIL']
password = os.environ['GOVEE_PASSWORD']
fifo_path = os.environ['GOVEE_FIFO_PATH']

if os.path.exists(fifo_path):
    os.remove(fifo_path)

os.mkfifo(fifo_path)

client = api.Govee(user, password, '')
client.login()
client.update_device_list()
devices = client.devices

while True:
    with open(fifo_path) as fifo:
        dev_id = fifo.read().replace('\n', '')
        if dev_id in devices:
            devices[dev_id].toggle()
